version: "3.9"

services:
  # Container Redis
  redis-movie:
    image: redis:7
    container_name: redis-movie
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Container PostgreSQL
  pg-db:
    image: postgres:15
    container_name: pg-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=T@McjBZn
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Ứng dụng Spring Boot
  movieapp:
    build: .
    container_name: movieapp
    ports:
      - "8080:8080"
    depends_on:
      - redis-movie
      - pg-db
    environment:
      # Ghi đè cấu hình để trỏ đúng vào tên service trong docker-compose
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-db:5432/movie_db
      - SPRING_DATA_REDIS_HOST=redis-movie
    restart: unless-stopped

volumes:
  redis-data:
  pg-data: